name: Generate and Publish Reports

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  generate-report:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "TIMESTAMP=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - uses: actions/checkout@v2
      
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - uses: actions/cache@v4
        with:
          path: .request_cache/**
          save-always: true
          key: request-cache-${{ hashFiles('request_cache.py') }}

      - run: |
          pip install -r requirements.txt

      - run: |
          python github_pr_analyzer.py --token ${{ secrets.REPORTS_GITHUB_TOKEN }} --github-owner opensearch-project --github-repo OpenSearch --cache-stats
      
      - run: |
          mkdir -p reports/${{ env.TIMESTAMP }}
          mv output/*.csv reports/${{ env.TIMESTAMP }}/
      
      - run: |
          python scripts/update_readme.py ${{ env.TIMESTAMP }}

      - name: Commit and push updates
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add README.md reports/
          git commit -m "Update reports and README for ${{ env.TIMESTAMP }}"
          git push
